// Generated by scripts/generate-runtime-config.js
const isLocalPreviewHost =
  typeof window !== "undefined"
  && /^(localhost|127\.0\.0\.1)$/i.test(window.location.hostname);

if (isLocalPreviewHost) {
  globalThis.MIRO_ALLOW_LOCAL_FALLBACK ??= true;
  globalThis.MIRO_BROWSER_VOICE_FALLBACK ??= true;
  globalThis.MIRO_API_BASE ??= "http://127.0.0.1:8101/api/v1";
  globalThis.MIRO_REVIEW_API_BASE ??= "http://127.0.0.1:8101/api/v1";
  globalThis.MIRO_SUPABASE_URL ??= "https://wzqpboqlhzxqbfautlxe.supabase.co";
  globalThis.MIRO_SUPABASE_PUBLISHABLE_KEY ??= "sb_publishable_U4xSHJ8_8kkDhYD8Q_a3Cw_HVJzZzZa";
  globalThis.MIRO_SUPABASE_AUTH_REDIRECT_TO ??= window.location.origin;
  globalThis.MIRO_TURNSTILE_SITE_KEY ??= "";
} else {
  globalThis.MIRO_ALLOW_LOCAL_FALLBACK ??= false;
  globalThis.MIRO_BROWSER_VOICE_FALLBACK ??= true;
  globalThis.MIRO_API_BASE ??= "/api/v1";
  globalThis.MIRO_REVIEW_API_BASE ??= "/api/v1";
  globalThis.MIRO_SUPABASE_URL ??= "";
  globalThis.MIRO_SUPABASE_PUBLISHABLE_KEY ??= "";
  globalThis.MIRO_SUPABASE_AUTH_REDIRECT_TO ??= "";
  globalThis.MIRO_TURNSTILE_SITE_KEY ??= "";
}
